/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  heroEyebrow?: string;
  heroHeading?: string;
  heroIntroduction?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  seoTitle?: string;
  seoDescription?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: string;
  order?: number;
  category?: "primary" | "interview";
  legacyId?: string;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  name?: string;
  role?: string;
  featured?: boolean;
  order?: number;
  legacyId?: string;
};

export type CleanoutProject = {
  _id: string;
  _type: "cleanoutProject";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  location?: string;
  description?: string;
  beforeImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  afterImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<
    {
      _key: string;
    } & ProjectPhoto
  >;
  published?: boolean;
  order?: number;
  completedAt?: string;
  legacyId?: string;
  legacyUrl?: string;
};

export type EstateSale = {
  _id: string;
  _type: "estateSale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  city?: string;
  status?: "draft" | "published" | "completed";
  biddingStarts?: string;
  biddingEnds?: string;
  pickup?: string;
  summary?: string;
  auctionUrl?: string;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  legacyId?: string;
  legacyUrl?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  eyebrow?: string;
  summary?: string;
  description?: string;
  image?: ImageWithAlt;
  features?: Array<string>;
  order?: number;
  heroEyebrow?: string;
  heroHeading?: string;
  heroIntroduction?: string;
  processSteps?: Array<
    {
      _key: string;
    } & ProcessStep
  >;
  seo?: SeoFields;
  category?: "estate-sales" | "clean-outs";
};

export type SeoFields = {
  _type: "seoFields";
  seoTitle?: string;
  seoDescription?: string;
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeading?: string;
  heroIntroduction?: string;
  directContactHeading?: string;
  directContactNote?: string;
  formHeading?: string;
  formIntro?: string;
  seo?: SeoFields;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeading?: string;
  heroIntroduction?: string;
  storyEyebrow?: string;
  storyHeading?: string;
  storyBody?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  valuesEyebrow?: string;
  valuesHeading?: string;
  values?: Array<
    {
      _key: string;
    } & ValueItem
  >;
  credentialsEyebrow?: string;
  credentialsHeading?: string;
  credentials?: Array<
    {
      _key: string;
    } & ValueItem
  >;
  seo?: SeoFields;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeading?: string;
  heroIntroduction?: string;
  heroProofPoints?: Array<string>;
  introEyebrow?: string;
  introHeading?: string;
  introBody?: string;
  processEyebrow?: string;
  processHeading?: string;
  processIntro?: string;
  processSteps?: Array<
    {
      _key: string;
    } & ProcessStep
  >;
  integrityEyebrow?: string;
  integrityHeading?: string;
  integrityBody?: string;
  integrityQuote?: string;
  integrityQuoteAttribution?: string;
  auctionBandEyebrow?: string;
  auctionBandHeading?: string;
  seo?: SeoFields;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  businessName?: string;
  shortName?: string;
  phone?: string;
  email?: string;
  serviceArea?: string;
  serviceAreaCities?: Array<string>;
  license?: string;
  auctionUrl?: string;
  facebookUrl?: string;
  instagramUrl?: string;
  twitterUrl?: string;
  contactName?: string;
  settlementNote?: string;
  brandMark?: ImageWithAlt;
  logo?: ImageWithAlt;
  defaultSeo?: SeoFields;
};

export type ValueItem = {
  _type: "valueItem";
  title?: string;
  body?: string;
  order?: number;
};

export type ProjectPhoto = {
  _type: "projectPhoto";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  stage?: "before" | "after" | "detail";
  caption?: string;
  alt?: string;
};

export type ProcessStep = {
  _type: "processStep";
  title?: string;
  body?: string;
  order?: number;
};

export type CtaLink = {
  _type: "ctaLink";
  label?: string;
  href?: string;
  openInNewTab?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Faq
  | Testimonial
  | CleanoutProject
  | EstateSale
  | Service
  | SeoFields
  | ImageWithAlt
  | ContactPage
  | AboutPage
  | HomePage
  | SiteSettings
  | ValueItem
  | ProjectPhoto
  | ProcessStep
  | CtaLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    businessName,    shortName,    phone,    email,    serviceArea,    serviceAreaCities,    license,    auctionUrl,    facebookUrl,    instagramUrl,    twitterUrl,    contactName,    settlementNote,    brandMark {  alt,  hotspot,  crop,  "url": asset->url,  "assetId": asset->_id},    logo {  alt,  hotspot,  crop,  "url": asset->url,  "assetId": asset->_id},    defaultSeo {  seoTitle,  seoDescription}  }
export type SITE_SETTINGS_QUERY_RESULT = {
  businessName: string | null;
  shortName: string | null;
  phone: string | null;
  email: string | null;
  serviceArea: string | null;
  serviceAreaCities: Array<string> | null;
  license: string | null;
  auctionUrl: string | null;
  facebookUrl: string | null;
  instagramUrl: string | null;
  twitterUrl: string | null;
  contactName: string | null;
  settlementNote: string | null;
  brandMark: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    url: string | null;
    assetId: string | null;
  } | null;
  logo: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    url: string | null;
    assetId: string | null;
  } | null;
  defaultSeo: {
    seoTitle: string | null;
    seoDescription: string | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0]{    heroEyebrow,    heroHeading,    heroIntroduction,    heroProofPoints,    introEyebrow,    introHeading,    introBody,    processEyebrow,    processHeading,    processIntro,    processSteps[] {  _key,  title,  body,  order},    integrityEyebrow,    integrityHeading,    integrityBody,    integrityQuote,    integrityQuoteAttribution,    auctionBandEyebrow,    auctionBandHeading,    seo {  seoTitle,  seoDescription}  }
export type HOME_PAGE_QUERY_RESULT = {
  heroEyebrow: string | null;
  heroHeading: string | null;
  heroIntroduction: string | null;
  heroProofPoints: Array<string> | null;
  introEyebrow: string | null;
  introHeading: string | null;
  introBody: string | null;
  processEyebrow: string | null;
  processHeading: string | null;
  processIntro: string | null;
  processSteps: Array<{
    _key: string;
    title: string | null;
    body: string | null;
    order: number | null;
  }> | null;
  integrityEyebrow: string | null;
  integrityHeading: string | null;
  integrityBody: string | null;
  integrityQuote: string | null;
  integrityQuoteAttribution: string | null;
  auctionBandEyebrow: string | null;
  auctionBandHeading: string | null;
  seo: {
    seoTitle: string | null;
    seoDescription: string | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage"][0]{    heroEyebrow,    heroHeading,    heroIntroduction,    storyEyebrow,    storyHeading,    storyBody,    valuesEyebrow,    valuesHeading,    values[] {  _key,  title,  body,  order},    credentialsEyebrow,    credentialsHeading,    credentials[] {  _key,  title,  body,  order},    seo {  seoTitle,  seoDescription}  }
export type ABOUT_PAGE_QUERY_RESULT = {
  heroEyebrow: string | null;
  heroHeading: string | null;
  heroIntroduction: string | null;
  storyEyebrow: string | null;
  storyHeading: string | null;
  storyBody: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  valuesEyebrow: string | null;
  valuesHeading: string | null;
  values: Array<{
    _key: string;
    title: string | null;
    body: string | null;
    order: number | null;
  }> | null;
  credentialsEyebrow: string | null;
  credentialsHeading: string | null;
  credentials: Array<{
    _key: string;
    title: string | null;
    body: string | null;
    order: number | null;
  }> | null;
  seo: {
    seoTitle: string | null;
    seoDescription: string | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage"][0]{    heroEyebrow,    heroHeading,    heroIntroduction,    directContactHeading,    directContactNote,    formHeading,    formIntro,    seo {  seoTitle,  seoDescription}  }
export type CONTACT_PAGE_QUERY_RESULT = {
  heroEyebrow: string | null;
  heroHeading: string | null;
  heroIntroduction: string | null;
  directContactHeading: string | null;
  directContactNote: string | null;
  formHeading: string | null;
  formIntro: string | null;
  seo: {
    seoTitle: string | null;
    seoDescription: string | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(order asc){    _id,    title,    "slug": slug.current,    eyebrow,    summary,    description,    image {  alt,  hotspot,  crop,  "url": asset->url,  "assetId": asset->_id},    features,    order,    heroEyebrow,    heroHeading,    heroIntroduction,    processSteps[] {  _key,  title,  body,  order},    seo {  seoTitle,  seoDescription},    category  }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  eyebrow: string | null;
  summary: string | null;
  description: string | null;
  image: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    url: string | null;
    assetId: string | null;
  } | null;
  features: Array<string> | null;
  order: number | null;
  heroEyebrow: string | null;
  heroHeading: string | null;
  heroIntroduction: string | null;
  processSteps: Array<{
    _key: string;
    title: string | null;
    body: string | null;
    order: number | null;
  }> | null;
  seo: {
    seoTitle: string | null;
    seoDescription: string | null;
  } | null;
  category: "clean-outs" | "estate-sales" | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: SERVICE_BY_SLUG_QUERY
// Query: *[_type == "service" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    eyebrow,    summary,    description,    image {  alt,  hotspot,  crop,  "url": asset->url,  "assetId": asset->_id},    features,    order,    heroEyebrow,    heroHeading,    heroIntroduction,    processSteps[] {  _key,  title,  body,  order},    seo {  seoTitle,  seoDescription},    category  }
export type SERVICE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  eyebrow: string | null;
  summary: string | null;
  description: string | null;
  image: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    url: string | null;
    assetId: string | null;
  } | null;
  features: Array<string> | null;
  order: number | null;
  heroEyebrow: string | null;
  heroHeading: string | null;
  heroIntroduction: string | null;
  processSteps: Array<{
    _key: string;
    title: string | null;
    body: string | null;
    order: number | null;
  }> | null;
  seo: {
    seoTitle: string | null;
    seoDescription: string | null;
  } | null;
  category: "clean-outs" | "estate-sales" | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(order asc){    _id,    quote,    name,    role,    featured,    order,    legacyId  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string | null;
  name: string | null;
  role: string | null;
  featured: boolean | null;
  order: number | null;
  legacyId: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: FAQS_QUERY
// Query: *[_type == "faq"] | order(order asc){    _id,    question,    answer,    order,    category,    legacyId  }
export type FAQS_QUERY_RESULT = Array<{
  _id: string;
  question: string | null;
  answer: string | null;
  order: number | null;
  category: "interview" | "primary" | null;
  legacyId: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: ESTATE_SALES_QUERY
// Query: *[_type == "estateSale" && status == "published"] | order(biddingEnds asc){    _id,    title,    city,    status,    biddingStarts,    biddingEnds,    pickup,    summary,    auctionUrl,    "featuredImage": featuredImage{      hotspot,      crop,      "url": asset->url,      "assetId": asset->_id    },    gallery[]{      _key,      hotspot,      crop,      "url": asset->url,      "assetId": asset->_id    },    legacyId,    legacyUrl  }
export type ESTATE_SALES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  city: string | null;
  status: "published";
  biddingStarts: string | null;
  biddingEnds: string | null;
  pickup: string | null;
  summary: string | null;
  auctionUrl: string | null;
  featuredImage: {
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    url: string | null;
    assetId: string | null;
  } | null;
  gallery: Array<{
    _key: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    url: string | null;
    assetId: string | null;
  }> | null;
  legacyId: string | null;
  legacyUrl: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CLEANOUT_PROJECTS_QUERY
// Query: *[_type == "cleanoutProject" && coalesce(published, true) == true] | order(order asc, completedAt desc){    _id,    title,    "slug": slug.current,    location,    description,    order,    published,    "photoCount": count(gallery[defined(image.asset)]),    "beforeImage": beforeImage{      alt,      hotspot,      crop,      "url": asset->url,      "assetId": asset->_id    },    "afterImage": afterImage{      alt,      hotspot,      crop,      "url": asset->url,      "assetId": asset->_id    },    completedAt  }
export type CLEANOUT_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  location: string | null;
  description: string | null;
  order: number | null;
  published: boolean | null;
  photoCount: number | null;
  beforeImage: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    url: string | null;
    assetId: string | null;
  } | null;
  afterImage: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    url: string | null;
    assetId: string | null;
  } | null;
  completedAt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CLEANOUT_PROJECT_BY_SLUG_QUERY
// Query: *[_type == "cleanoutProject" && slug.current == $slug && coalesce(published, true) == true][0]{    _id,    title,    "slug": slug.current,    location,    description,    completedAt,    "beforeImage": beforeImage{      alt,      hotspot,      crop,      "url": asset->url,      "assetId": asset->_id    },    "afterImage": afterImage{      alt,      hotspot,      crop,      "url": asset->url,      "assetId": asset->_id    },    "gallery": gallery[defined(image.asset)] {  _key,  stage,  caption,  alt,  "image": image{    hotspot,    crop,    "url": asset->url,    "assetId": asset->_id  }}  }
export type CLEANOUT_PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  location: string | null;
  description: string | null;
  completedAt: string | null;
  beforeImage: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    url: string | null;
    assetId: string | null;
  } | null;
  afterImage: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    url: string | null;
    assetId: string | null;
  } | null;
  gallery: Array<{
    _key: string;
    stage: "after" | "before" | "detail" | null;
    caption: string | null;
    alt: string | null;
    image: {
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      url: string | null;
      assetId: string | null;
    } | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0]{\n    businessName,\n    shortName,\n    phone,\n    email,\n    serviceArea,\n    serviceAreaCities,\n    license,\n    auctionUrl,\n    facebookUrl,\n    instagramUrl,\n    twitterUrl,\n    contactName,\n    settlementNote,\n    brandMark {\n  alt,\n  hotspot,\n  crop,\n  "url": asset->url,\n  "assetId": asset->_id\n},\n    logo {\n  alt,\n  hotspot,\n  crop,\n  "url": asset->url,\n  "assetId": asset->_id\n},\n    defaultSeo {\n  seoTitle,\n  seoDescription\n}\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "homePage"][0]{\n    heroEyebrow,\n    heroHeading,\n    heroIntroduction,\n    heroProofPoints,\n    introEyebrow,\n    introHeading,\n    introBody,\n    processEyebrow,\n    processHeading,\n    processIntro,\n    processSteps[] {\n  _key,\n  title,\n  body,\n  order\n},\n    integrityEyebrow,\n    integrityHeading,\n    integrityBody,\n    integrityQuote,\n    integrityQuoteAttribution,\n    auctionBandEyebrow,\n    auctionBandHeading,\n    seo {\n  seoTitle,\n  seoDescription\n}\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "aboutPage"][0]{\n    heroEyebrow,\n    heroHeading,\n    heroIntroduction,\n    storyEyebrow,\n    storyHeading,\n    storyBody,\n    valuesEyebrow,\n    valuesHeading,\n    values[] {\n  _key,\n  title,\n  body,\n  order\n},\n    credentialsEyebrow,\n    credentialsHeading,\n    credentials[] {\n  _key,\n  title,\n  body,\n  order\n},\n    seo {\n  seoTitle,\n  seoDescription\n}\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_type == "contactPage"][0]{\n    heroEyebrow,\n    heroHeading,\n    heroIntroduction,\n    directContactHeading,\n    directContactNote,\n    formHeading,\n    formIntro,\n    seo {\n  seoTitle,\n  seoDescription\n}\n  }\n': CONTACT_PAGE_QUERY_RESULT;
    '\n  *[_type == "service"] | order(order asc){\n    _id,\n    title,\n    "slug": slug.current,\n    eyebrow,\n    summary,\n    description,\n    image {\n  alt,\n  hotspot,\n  crop,\n  "url": asset->url,\n  "assetId": asset->_id\n},\n    features,\n    order,\n    heroEyebrow,\n    heroHeading,\n    heroIntroduction,\n    processSteps[] {\n  _key,\n  title,\n  body,\n  order\n},\n    seo {\n  seoTitle,\n  seoDescription\n},\n    category\n  }\n': SERVICES_QUERY_RESULT;
    '\n  *[_type == "service" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    eyebrow,\n    summary,\n    description,\n    image {\n  alt,\n  hotspot,\n  crop,\n  "url": asset->url,\n  "assetId": asset->_id\n},\n    features,\n    order,\n    heroEyebrow,\n    heroHeading,\n    heroIntroduction,\n    processSteps[] {\n  _key,\n  title,\n  body,\n  order\n},\n    seo {\n  seoTitle,\n  seoDescription\n},\n    category\n  }\n': SERVICE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "testimonial"] | order(order asc){\n    _id,\n    quote,\n    name,\n    role,\n    featured,\n    order,\n    legacyId\n  }\n': TESTIMONIALS_QUERY_RESULT;
    '\n  *[_type == "faq"] | order(order asc){\n    _id,\n    question,\n    answer,\n    order,\n    category,\n    legacyId\n  }\n': FAQS_QUERY_RESULT;
    '\n  *[_type == "estateSale" && status == "published"] | order(biddingEnds asc){\n    _id,\n    title,\n    city,\n    status,\n    biddingStarts,\n    biddingEnds,\n    pickup,\n    summary,\n    auctionUrl,\n    "featuredImage": featuredImage{\n      hotspot,\n      crop,\n      "url": asset->url,\n      "assetId": asset->_id\n    },\n    gallery[]{\n      _key,\n      hotspot,\n      crop,\n      "url": asset->url,\n      "assetId": asset->_id\n    },\n    legacyId,\n    legacyUrl\n  }\n': ESTATE_SALES_QUERY_RESULT;
    '\n  *[_type == "cleanoutProject" && coalesce(published, true) == true] | order(order asc, completedAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    location,\n    description,\n    order,\n    published,\n    "photoCount": count(gallery[defined(image.asset)]),\n    "beforeImage": beforeImage{\n      alt,\n      hotspot,\n      crop,\n      "url": asset->url,\n      "assetId": asset->_id\n    },\n    "afterImage": afterImage{\n      alt,\n      hotspot,\n      crop,\n      "url": asset->url,\n      "assetId": asset->_id\n    },\n    completedAt\n  }\n': CLEANOUT_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "cleanoutProject" && slug.current == $slug && coalesce(published, true) == true][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    location,\n    description,\n    completedAt,\n    "beforeImage": beforeImage{\n      alt,\n      hotspot,\n      crop,\n      "url": asset->url,\n      "assetId": asset->_id\n    },\n    "afterImage": afterImage{\n      alt,\n      hotspot,\n      crop,\n      "url": asset->url,\n      "assetId": asset->_id\n    },\n    "gallery": gallery[defined(image.asset)] {\n  _key,\n  stage,\n  caption,\n  alt,\n  "image": image{\n    hotspot,\n    crop,\n    "url": asset->url,\n    "assetId": asset->_id\n  }\n}\n  }\n': CLEANOUT_PROJECT_BY_SLUG_QUERY_RESULT;
  }
}
